name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hub
        uses: huggingface/github-sync-action@v2
        with:
          github_repo: tsrinath2007/Life-Support-ENV
          huggingface_repo: tsrinath/Life-Support-ENV
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
